function [] = run_end_message(window, tpoints, points_structure, ...
    screenYpixels, badge_rects, badge_tex, time)

    % text info here
    Screen('TextStyle', window, 1);
    Screen('TextSize', window, 20);
    instruct_col = [49, 130, 189];
    
    % get the badges unlocked 
    badge_break = sum(tpoints >= points_structure);

    motivation_instructions = sprintf(['Nicely done! \n\n', ...
        'Thanks for your hard work!' ...
        ]);

    if badge_break == 1
        badge_instructions = sprintf(...
            ['You scored %d points\n'...
            'You are Lowly Llama!\n'],...
            tpoints);

    elseif badge_break == 2
        badge_instructions = sprintf(...
            ['You have scored %d points. \n'...
            'You are Novice Narwhal!\n'],...
            tpoints);

    elseif badge_break == 3
        badge_instructions = sprintf(...
            ['You have scored %d points\n'...
            'You are Awesome Anteater!\n'],...
            tpoints);

    elseif badge_break == 4
        badge_instructions = sprintf(...
            ['You scored %d points\n'...
            'You are Radiant Rhinocerous!\n'...
            'The animals whisper your name now...\n'...
            'You live on in their legends.'], tpoints);
    end


    draw_badges(window, tpoints >= points_structure, badge_rects, badge_tex);
    DrawFormattedText(window, motivation_instructions, 'Center', screenYpixels*.5, instruct_col);
    DrawFormattedText(window, badge_instructions, 'Center', screenYpixels*.6, instruct_col);
    Screen('Flip', window);

    KbWait;
    WaitSecs(time.wait_after_instruct);
