function [] = run_n_back_instructions(window, screenYpixels, time)

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instruct_col = [49, 130, 189];

instructions = ...
    sprintf(['Nice one!\n\n'...
             'While we give the animals some time to rest, you are now going\n' ...
             'to undertake an audio-based task. \n\n'...
             'During this task, you will hear a series of letters. \n\n' ...
             'Your goal is to identify every time you hear a letter that matches\n'...
             'the letter that you heard 2 places beforehand.\n\n'...
             'Press any key to continue with the instructions.'
             ]);

DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
Screen('Flip', window);

KbWait;
WaitSecs(time.wait_after_instruct);

instructions = ...
    sprintf(['For example, if you heard the letters "K", "V", "K", "Q", "Q"\n' ...
             'a correct response would be pressing the "z" key on the second "K". \n\n'...
             'During the task, you should not press the "z" key under any \n' ...
             'other circumstances \n\n' ...
             'You will now practice this audio task.\n'...
             'Place your finger on the "z" key now.\n\n'...
             'Press any key to start the task.'
             ]);

DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
Screen('Flip', window);
