function [] = run_multi_instructions_block(window, screenYpixels, time, ...
    count_blocks, nblocks, current_block_type)

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instruct_col = [49, 130, 189];

progress = sprintf('Block %d of %d!\n\n', count_blocks, nblocks);

if current_block_type == 1
    block_instruct = sprintf(['You are tasked with only finding animals. \n\n'...
        'Remember, the house they are in may change from time to time. \n\n'...
        'Just like you practiced. \n\n' ...
        'No auditory task this time.\n\n'...
        'Remember, points are on the line, as are prizes!\n\n'...
        'You`ve got this!\n\n'...
        'Place a hand on the mouse, and press any key to start' ...
        ]);
else

    block_instruct = sprintf(['Time to multitask!\n\n'...
        'You are tasked with finding the animals. \n\n'...
        'Remember, the house they are in may change from time to time. \n\n'...
        'You will also do the auditory task. \n' ...
        'So be ready to hit the `z` key! \n' ...
        'But only when you hear the same letter as two letters ago. \n'...
        'Just like you practiced. \n\n' ...
        'Give this your best shot! There are points to be won. \n' ...
        'And prizes! \n\n' ...
        'Place a hand on the mouse, and line your finger up on the `z` key. \n' ...
        'Press any key to start the block.'
        ]);
end

DrawFormattedText(window, progress, 'Center', screenYpixels*.3, instruct_col);
DrawFormattedText(window, block_instruct, 'Center', screenYpixels*.4, instruct_col);
Screen('Flip', window);

KbWait;
WaitSecs(time.wait_after_instruct);