function [] = run_multi_instructions_main(window, screenYpixels, time, badge_rects,...
    badge_tex, points_structure)

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instruct_col = [49, 130, 189];

instructions = ...
    sprintf(['Nice work!\n\n\n' ...
    'Now, we are going to put all the skills you have learnt to the test… \n\n' ...
    'Pay attention, because now you are playing for ˖⁺‧₊˚✦ points! ✦˖⁺‧₊˚ \n' ...
    'Buuuut ONLY if you find the animal within 4 moves.\n\n'...
    'Outstanding performance across all tasks will reward you not only with points,\n' ...
    'But possibly ˖⁺‧₊˚✦ prizes! ✦˖⁺‧₊˚!\n\n\n'...,
    'Note that points will not be available on every trial. If you get the animal\n'...
    'in less than 4 moves and you don`t hear a sound, then there were no points that time.\n\n\n\n'...
    'Now, press any key to learn what these points will earn you!']);
DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
Screen('Flip', window);
KbWait();
WaitSecs(time.wait_after_instruct);

instructions = ...
    sprintf(['If you win enough points, you can unlock some coveted badges!\n\n\n'...
    '%d points = Lowly Llama achieved\n'...
    '%d = Novice Narwhal attained\n'...
    '%d = Awesome Anteater unlocked\n'...
    '%d points = The rare Radiant Rhinocerous will be yours!\n\n\n'...
    'Many pass through these doors, yet not many can call themselves Radiant Rhinocerous...\n\n\n\n'...
    'Press any key to continue.'], points_structure(1), points_structure(2),...
    points_structure(3), points_structure(4));
draw_badges(window, [1, 1, 1, 1], badge_rects, badge_tex);
DrawFormattedText(window, instructions,'Center', screenYpixels*.5, instruct_col);
Screen('Flip', window);