function [] = run_multi_instructions_practice(window, screenYpixels, time)

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instruct_col = [49, 130, 189];

instructions = ...
    sprintf(['Ready to practice your last task?\n\n'...
             'From now, you search for the animals\n' ...
             'and you will do the audio task as the same time. \n\n'...
             'Just like before, the animals are hiding in the two houses, and \n' ...
             'no border will be present. The animals will only hide in the same positions\n'...
             'as they did when the coloured borders were present. \n\n' ...
             'Press any key to read just a few more instructions.'
             ]);

DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
Screen('Flip', window);

KbWait;
WaitSecs(time.wait_after_instruct);

instructions = ...
    sprintf(['Remember, if you hear a letter and it was the same as 2 letters ago' ...
             'Then press the "z" key.' ...
             'For example, if you heard the letters "K", "V", "K", "Q", "Q"\n' ...
             'a correct response would be pressing the "z" key on hearing the second "K". \n\n'...
             'During the task, you would not press the "z" key under any \n' ...
             'other circumstances \n\n' ...
             'Please place your finger on the "z" key now.\n\n'...
             'Press any key to start the practice.'
             ]);

DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
Screen('Flip', window);
