function [] = run_badge_feedback(window, tpoints, points_structure, ...
    screenYpixels, badge_rects, badge_tex, time)

    % text info here
    Screen('TextStyle', window, 1);
    Screen('TextSize', window, 20);
    instruct_col = [49, 130, 189];
    
    % get the badges unlocked 
    badge_break = sum(tpoints >= points_structure);

    motivation_instructions = sprintf('Well done! \n\n');

    if ~badge_break
        badge_instructions = sprintf(...
            ['You have scored %d points so far\n'...
            'You need %d points to achieve Lowly Llama!\n\n'],...
             tpoints, points_structure(1));

    elseif badge_break == 1
        badge_instructions = sprintf(...
            ['You have scored %d points so far\n'...
            'You are now of rank Lowly Llama!\n'...
            'You need %d points to unlock Novice Narwhal!\n\n'],...
            tpoints, points_structure(2));

    elseif badge_break == 2
        badge_instructions = sprintf(...
            ['You have scored %d points so far\n'...
            'You unlocked Novice Narwhal\n'...
            'You need %d points to unlock Awesome Anteater!\n\n'],...
            tpoints, points_structure(3));

    elseif badge_break == 3
        badge_instructions = sprintf(...
            ['You have scored %d points so far\n'...
            'Rank Awesome Anteater achieved.\n'...
            'You need %d points to unlock Radiant Rhinocerous!\n\n'],...
            tpoints, points_structure(4)); 

    elseif badge_break == 4
        badge_instructions = sprintf(...
            ['You have scored %d points so far\n'...
            'You are a Radiant Rhinocerous!\n'...
            'The animals whisper your name now...\n'...
            'You live on in their legends.'], tpoints);
    end


    final_instructions = sprintf(...
        ['Also, take a break...you earned it.\n\n'...
        'Press any key to continue.\n']);

    draw_badges(window, tpoints >= points_structure, badge_rects, badge_tex);
    DrawFormattedText(window, motivation_instructions, 'Center', screenYpixels*.5, instruct_col);
    DrawFormattedText(window, badge_instructions, 'Center', screenYpixels*.6, instruct_col);
    DrawFormattedText(window, final_instructions, 'Center', screenYpixels*.8, instruct_col);
    Screen('Flip', window);

    KbWait;
    WaitSecs(time.wait_after_instruct);
